### ISSUE TITLE
edfx_database.truncate_eeg(sleep)

### ISSUE THREAD

**Issue by gadallon1** [skjerns/AutoSleepScorerDev#1]
When I am running run_sample.py, everything seems to work well, until I get to the line:
edfx_database.truncate_eeg(sleep)

I am getting the following error message: 

OSError                                   Traceback (most recent call last)
<ipython-input-68-de7807cbc76f> in <module>()
----> 1 edfx_database.truncate_eeg(sleep)

~/Dropbox/Research/sleep lab/AutoSleepScorerDev-master/edfx_database.py in truncate_eeg(sleepdataset)
    106     sleep.data = new_data
    107     sleep.hypno = new_hypno
--> 108     sleep.save_object()
    109 
    110 def prepare(datadir = 'edfx'):

~/Dropbox/Research/sleep lab/AutoSleepScorerDev-master/sleeploader.py in save_object(self, filename, path)
    359         print('Saving data at {}'.format(filename))
    360         with open(os.path.join(path, filename), 'wb') as f:
--> 361             cPickle.dump(self.__dict__,f,2)
    362 
    363 

OSError: [Errno 22] Invalid argument

**Comment by skjerns** [comment]
Which Python version are you using?

Try redownloading the EDFx database. You can do that automatically by deleting the `edfx` folder where the script is

**Comment by gadallon1** [comment]
I am using Python 3.6.3.
I tried doing it and got the same outcome. 
After it downloaded all files. 

" Saving data at sleepdata.pkl
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-23-428ccf5f2f98> in <module>()
      7     # use float16 is you have problems with memory or a small hard disk.  Should be around 2.6 GB for float32.
      8     sleep.load( channels = channels, references = references, verbose=0, dtype=np.float32)
----> 9     edfx_database.truncate_eeg(sleep)
     10 else:
     11     sleep = sleeploader.SleepDataset(datadir)

~/Dropbox/Research/Sleep Lab/AutoSleepScorerDev-master/edfx_database.py in truncate_eeg(sleepdataset)
    106     sleep.data = new_data
    107     sleep.hypno = new_hypno
--> 108     sleep.save_object()
    109 
    110 def prepare(datadir = 'edfx'):

~/Dropbox/Research/Sleep Lab/AutoSleepScorerDev-master/sleeploader.py in save_object(self, filename, path)
    359         print('Saving data at {}'.format(filename))
    360         with open(os.path.join(path, filename), 'wb') as f:
--> 361             cPickle.dump(self.__dict__,f,2)
    362 
    363 

OSError: [Errno 22] Invalid argument"

**Comment by skjerns** [comment]
I'm sorry, I can't reproduce the error on my computer.

**Comment by gadallon1** [comment]
Let me try and delve deeper into it and see what may be causing it.



On Jan 3, 2018, at 3:41 AM, skjerns <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm sorry, I can't reproduce the error on my computer.
