### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by balandongiv** [skjerns/AutoSleepScorerDev#2]
Dear Simon, GREAT project you have here.
May I know the environment you have when developing the framework here. Specifically,
The version of the following packages:
1) **Phyton x.x.x**
2) **Tensorflow x.x** gpu/cpu?
3) **Keras x.x.x**

and, if the framework required
**CUDA toolkit or  CuDNN**

Not that important, but helpful you can share what version of **Ubuntu xx.xx**?

I hope I can troubleshoot more effectively by knowing all these informations. 

Just wonder if you are familiar with [Docker](https://www.docker.com), maybe you can share an image off the environment when developing this framework.

Best wishes,
Rodney

**Comment by skjerns** [comment]
1. Python 3.6
2. Tensorflow 1.4
3. Keras 2.0
4. CUDA 8.0 + CuDNN
5.  I'm using Windows 10 for prototyping ( ;-) ) and a cluster running bullx Linux for training

But it should work with any versions of this.

I'm familiar with Docker, but right now I lack the time to develop this project further.

**Comment by balandongiv** [comment]
Hi Simon, thanks for the input, really appreciate it. It is safe to assume you were using [CuDNN version 5](https://developer.nvidia.com/rdp/cudnn-archive#collapseTwo), right.

Thanks in advance.

**Comment by skjerns** [comment]
5.1 or 6.0, should not make a big difference
