### ISSUE TITLE
What is the difference between target and groups?

### ISSUE THREAD

**Issue by balandongiv** [skjerns/AutoSleepScorerDev#5]
Hi Simon,
May I know what is the difference between target and groups in the script [run_sample.py](https://github.com/skjerns/AutoSleepScorerDev/blob/master/run_sample.py) of line 35. Quick check the values on these two variables showed no differences between them.

Thanks for the time entertaining this question.

**Comment by skjerns** [comment]
That should not be the case. If I remember correctly `target` has the sleep stages and `group` denotes the subject ID. That means all epochs with the same group ID belong to the same night/subject.

**Comment by balandongiv** [comment]
Yes, now the value make sense to me. Thanks for the prompt reply
